networks:
  web:
    external: true
  lan:
    external: false
    name: lan_${NAME}

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - web
      - lan
    command: >
      sh -c "
      if [ -f kameleon_back/settings.py ]; then
        # Ajouter django.jrcan.dev à ALLOWED_HOSTS
        grep -qxF \"ALLOWED_HOSTS = ['kameleonback.jrcan.dev']\" kameleon_back/settings.py || \
        sed -i \"/^ALLOWED_HOSTS/c\\ALLOWED_HOSTS = ['kameleonback.jrcan.dev']\" kameleon_back/settings.py;
      fi &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    labels:
      - traefik.enable=true

      # Route "HTTP normal" sur le host kameleonback.jrcan.dev
      - traefik.http.routers.kameleonback.entryPoints=websecure
      - traefik.http.routers.kameleonback.rule=Host(`kameleonback.jrcan.dev`)
      - traefik.http.routers.kameleonback.tls=true
      - traefik.http.routers.kameleonback.tls.certresolver=myresolver
      - traefik.http.services.kameleonback.loadbalancer.server.port=8000

      # Route WebSocket
      - traefik.http.routers.kameleonback-ws.entryPoints=websecure
      - traefik.http.routers.kameleonback-ws.rule=Host(`kameleonback.jrcan.dev`) && PathPrefix(`/ws`)
      - traefik.http.routers.kameleonback-ws.service=kameleonback
      - traefik.http.routers.kameleonback.priority=1
      - traefik.http.routers.kameleonback-ws.priority=2

      # (Optionnel) Pour forcer le header X-Forwarded-Proto
      - traefik.http.middlewares.kameleonback-ws.headers.customrequestheaders.X-Forwarded-Proto=https

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lan

  redis:
    image: redis:alpine
    networks:
      - lan

volumes:
  postgres_data: