# Generated by Django 5.1.3 on 2024-11-19 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('last_connection', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('clan_id', models.AutoField(primary_key=True, serialize=False)),
                ('clan_name', models.CharField(max_length=100)),
                ('clan_elo', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('cv_file', models.FileField(upload_to='cvs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('rank_name', models.CharField(max_length=50)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='rank_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('riddle_id', models.AutoField(primary_key=True, serialize=False)),
                ('riddle_type', models.CharField(max_length=50)),
                ('riddle_variable', models.TextField()),
                ('riddle_response', models.TextField()),
                ('riddle_difficulty', models.IntegerField()),
                ('riddle_theme', models.CharField(max_length=100)),
                ('riddle_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VersusRiddleImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(upload_to='versus_riddles/')),
                ('image_step', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('member_score', models.FloatField(default=0.0)),
                ('member_clan_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.cv'),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.rank'),
        ),
        migrations.CreateModel(
            name='SoloRiddle',
            fields=[
                ('riddle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='back.riddle')),
                ('riddle_image', models.ImageField(blank=True, null=True, upload_to='solo_riddles/')),
            ],
        ),
        migrations.CreateModel(
            name='VersusRiddle',
            fields=[
                ('riddle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='back.riddle')),
                ('versus_nb_step', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.riddle')),
            ],
        ),
        migrations.CreateModel(
            name='Compete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_used', models.BooleanField(default=False)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.clan')),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.riddle')),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('clue_id', models.AutoField(primary_key=True, serialize=False)),
                ('clue_text', models.TextField()),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.riddle')),
            ],
        ),
        migrations.CreateModel(
            name='HasImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.riddle')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.versusriddleimage')),
            ],
        ),
        migrations.AddField(
            model_name='versusriddleimage',
            name='riddle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.versusriddle'),
        ),
    ]
